### ISSUE TITLE
Palaeogenetics lab at BioArCh York

### ISSUE THREAD

**Issue by eg715** [SPAAM-community/ancient-metagenomics-labs#8]
The link to our webpage is here: https://www.york.ac.uk/archaeology/centres-facilities/bioarch/facilities/palaeogenomics/

Our PI is Dr. Nathan Wales who's page is here: https://www.york.ac.uk/archaeology/people/academic-staff/wales/

We complete projects and train on all and each element of a palaeogenetics project from sample choice, wet lab procedures in our bespoke facilities to bioinformatic analysis using the super computer at the Univeristy of York - Viking: https://www.york.ac.uk/it-services/services/viking-computing-cluster/

Our material focus is very broad, we work on human and animal bone, plant remains and other novel substrates such as coprolites (preserved faeces) and grinding stones to address specific archaeological questions.

**Comment by jfy133** [comment]
Added in: https://github.com/SPAAM-community/ancient-metagenomics-labs/commit/96f2913365a06baff101edf6a7998c63f6336a59
