### ISSUE TITLE
Ancient Environmental Genomics MPRG [AEG]

### ISSUE THREAD

**Issue by bvernot** [SPAAM-community/ancient-metagenomics-labs#9]
### Name of Lab

Ancient Environmental Genomics MPRG

### Name of PI

Dr. Benjamin Vernot

### Name of Institution

Max-Planck-Institut für evolutionäre Anthropologie

### Country of Institution

Germany

### Webpage of the lab or group

https://www.eva.mpg.de/genetics/ancient-environmental-genomics/

### Research focus

- [X] anthropogenic
- [X] environmental
- [ ] host-associated
- [ ] microbial-genomics

### Other information

We study human history / population genetics from environmental DNA.

**Comment by jfy133** [comment]
Thanks @bvernot ! Website should be updated: https://spaam-community.github.io/ancient-metagenomics-labs/#/ let me know if you see any issues

**Comment by jfy133** [comment]
Note I've listed it under 'EVA' as I presume we are sharing the same labs

**Comment by bvernot** [comment]
Looks great, thank you!
